print("Llena los datos para crear tu historia")
nombre = input () 
puesto = input () 
adjetivo1 = input () 
adjetivo2 = input () 
comida1 = input () 
comida2 = input ()  
sentimiento = input () 

print(f"{nombre} ha comenzado hoy su primer curso de Generetion.")
print(f"Se están formando como {puesto}")
print(f"Su compañero les pareció muy {adjetivo1}, pero su profesor era, cuando menos {adjetivo2}.")
print(f"Para comer comen {comida1} y {comida2} mientras repasan sus notas.")
print(f"Sienten {sentimiento} pero están decididos a completar el curso.")